import './styles.css';

type Branch = { id: string; name: string; code: string; address?: string };
type Table = { id: string; name: string; capacity: number; status: string };
type Variant = { id: string; name: string; price: number };
type Product = { id: string; name: string; description?: string; category_name: string; is_available: boolean; variants: Variant[] };
type CartLine = { product: Product; variant: Variant; quantity: number };
type User = { id: string; email?: string; name?: string; roles?: string[] };
type KitchenTicket = { id: string; folio?: string | number; kitchen_status?: string; items?: { product_name: string; variant_name?: string; quantity: number }[]; created_at?: string };

const api = async <T>(path: string, options: RequestInit = {}): Promise<T> => {
  const response = await fetch(path, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...options.headers }, ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || `Error ${response.status}`);
  return body as T;
};

const state: { user?: User; branches: Branch[]; branch?: Branch; tables: Table[]; menu: Product[]; cart: CartLine[]; view: 'meseros' | 'cocina'; loading: boolean; error: string; connected: boolean; kitchen: KitchenTicket[]; kitchenPending: boolean } = {
  branches: [], tables: [], menu: [], cart: [], view: 'meseros', loading: false, error: '', connected: true, kitchen: [], kitchenPending: false,
};
let kitchenStream: EventSource | undefined;
const root = document.querySelector<HTMLDivElement>('#app')!;
const money = (value: number) => new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(value);
const esc = (value: unknown) => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char] || char);
const total = () => state.cart.reduce((sum, line) => sum + line.variant.price * line.quantity, 0);
const setBusy = (busy: boolean) => { state.loading = busy; render(); };
const showError = (error: unknown) => { state.error = error instanceof Error ? error.message : 'No fue posible completar la operación'; state.connected = true; render(); };

function render(): void {
  if (!state.user) { renderLogin(); return; }
  root.innerHTML = `<div class="app-shell">
    <header class="topbar"><div class="brand"><span class="brand-mark">G</span><div><strong>GorditasOS</strong><small>Operación diaria</small></div></div>
      <div class="top-actions"><span class="connection ${state.connected ? 'online' : 'offline'}"><i></i>${state.connected ? 'Conectado' : 'Sin conexión'}</span><button class="ghost" id="logout">Salir</button></div></header>
    <main><div class="page-heading"><div><p class="eyebrow">${state.view === 'meseros' ? 'Sala y pedidos' : 'Producción'}</p><h1>${state.view === 'meseros' ? 'Toma de pedidos' : 'Cocina'}</h1></div>
      <select id="branch" aria-label="Sucursal activa">${state.branches.map(branch => `<option value="${branch.id}" ${branch.id === state.branch?.id ? 'selected' : ''}>${esc(branch.name)} · ${esc(branch.code)}</option>`).join('')}</select></div>
      <nav class="tabs"><button class="${state.view === 'meseros' ? 'active' : ''}" data-view="meseros">Meseros</button><button class="${state.view === 'cocina' ? 'active' : ''}" data-view="cocina">Cocina</button></nav>
      ${state.error ? `<div class="alert error">${esc(state.error)}<button id="clear-error" aria-label="Cerrar error">×</button></div>` : ''}
      ${state.view === 'meseros' ? waiterView() : kitchenView()}
    </main></div>`;
  bindCommon();
  if (state.view === 'meseros') bindWaiter(); else bindKitchen();
}

function renderLogin(): void { root.innerHTML = `<main class="login-page"><section class="login-art"><span class="brand-mark">G</span><p class="eyebrow">Operación multisucursal</p><h1>El servicio empieza aquí.</h1><p>Pedidos claros, cocina sincronizada y una operación que sigue el ritmo de tu equipo.</p></section><section class="login-panel"><div><p class="eyebrow">Bienvenido</p><h2>Iniciar sesión</h2><p class="muted">Usa tu cuenta autorizada para continuar.</p></div><form id="login-form"><label>Correo electrónico<input name="email" type="email" autocomplete="username" required placeholder="tu@restaurante.mx"></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required></label><button class="primary wide" type="submit" ${state.loading ? 'disabled' : ''}>${state.loading ? 'Entrando…' : 'Entrar a la operación'}</button></form>${state.error ? `<div class="alert error">${esc(state.error)}</div>` : ''}<p class="login-note">Sesión protegida con cookie segura.</p></section></main>`;
  document.querySelector<HTMLFormElement>('#login-form')!.onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); setBusy(true); try { await api('/api/v1/auth/login', { method: 'POST', body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); await loadSession(); } catch (error) { state.loading = false; showError(error); } };
}

function waiterView(): string { const categories = [...new Set(state.menu.map(product => product.category_name))]; return `<div class="workspace"><section class="menu-panel"><div class="section-head"><div><h2>Menú disponible</h2><p class="muted">Toca un artículo para agregarlo al pedido.</p></div><span class="count">${state.menu.length} artículos</span></div>${state.menu.length ? categories.map(category => `<div class="category"><h3>${esc(category)}</h3><div class="product-grid">${state.menu.filter(product => product.category_name === category).map(product => `<article class="product ${!product.is_available ? 'disabled' : ''}"><div><h4>${esc(product.name)}</h4><p>${esc(product.description || 'Preparado al momento')}</p></div><div class="product-bottom"><span>${product.is_available ? money(product.variants[0]?.price || 0) : 'Agotado'}</span><button class="add" data-product="${product.id}" ${product.is_available ? '' : 'disabled'} aria-label="Agregar ${esc(product.name)}">+</button></div></article>`).join('')}</div></div>`).join('') : '<div class="empty"><strong>Menú no disponible</strong><p>Selecciona una sucursal con catálogo activo.</p></div>'}</section><aside class="order-panel"><div class="section-head"><div><p class="eyebrow">Nueva comanda</p><h2>Pedido actual</h2></div><span class="order-status">Borrador</span></div><label class="compact-label">Mesa<select id="table"><option value="">Para llevar</option>${state.tables.filter(table => table.status !== 'DISABLED').map(table => `<option value="${table.id}">${esc(table.name)} · ${table.capacity} lugares</option>`).join('')}</select></label><div class="cart">${state.cart.length ? state.cart.map((line, index) => `<div class="cart-line"><div><strong>${esc(line.product.name)}</strong><small>${esc(line.variant.name)} · ${money(line.variant.price)}</small></div><div class="quantity"><button data-cart="${index}" data-change="-1">−</button><b>${line.quantity}</b><button data-cart="${index}" data-change="1">+</button></div></div>`).join('') : '<div class="empty cart-empty"><span>＋</span><strong>Tu pedido está vacío</strong><p>Agrega artículos del menú.</p></div>'}</div><div class="order-total"><span>Total estimado</span><strong>${money(total())}</strong></div><button class="primary wide" id="send-order" ${state.cart.length && !state.loading ? '' : 'disabled'}>${state.loading ? 'Enviando…' : 'Confirmar y enviar a cocina'}</button></aside></div>`; }

function kitchenView(): string { return `<section class="kitchen-view"><div class="section-head"><div><h2>Comandas pendientes</h2><p class="muted">Actualización automática cada 15 segundos.</p></div><button class="secondary" id="refresh-kitchen">↻ Actualizar</button></div>${state.kitchenPending ? '<div class="empty"><strong>El módulo de cocina está pendiente</strong><p>La API actual no expone una acción separada de aceptar. Consulta el contrato en el README.</p></div>' : state.kitchen.length ? `<div class="ticket-grid">${state.kitchen.map(ticket => { const status = ticket.kitchen_status || ''; return `<article class="ticket"><div class="ticket-top"><strong>#${esc(ticket.folio || ticket.id.slice(0, 6))}</strong><span>${esc(status)}</span></div><small>${ticket.created_at ? new Date(ticket.created_at).toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit' }) : ''}</small><ul>${(ticket.items || []).map(item => `<li><b>${item.quantity}×</b> ${esc(item.product_name)} ${esc(item.variant_name || '')}</li>`).join('')}</ul><div class="ticket-actions">${status === 'PENDING' ? `<button class="primary" data-kitchen="start" data-id="${ticket.id}">Iniciar</button>` : ''}${status === 'IN_PROGRESS' ? `<button class="primary" data-kitchen="ready" data-id="${ticket.id}">Marcar listo</button>` : ''}</div></article>`; }).join('')}</div>` : '<div class="empty"><strong>Todo al día</strong><p>No hay comandas pendientes en esta sucursal.</p></div>'}</section>`; }

function bindCommon(): void { document.querySelector('#logout')!.addEventListener('click', async () => { await api('/api/v1/auth/logout', { method: 'POST' }).catch(() => undefined); state.user = undefined; render(); }); document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(button => button.onclick = () => { state.view = button.dataset.view as 'meseros' | 'cocina'; render(); loadBranchData(); }); document.querySelector<HTMLSelectElement>('#branch')!.onchange = event => { state.branch = state.branches.find(branch => branch.id === (event.target as HTMLSelectElement).value); loadBranchData(); }; document.querySelector('#clear-error')?.addEventListener('click', () => { state.error = ''; render(); }); }
function bindWaiter(): void { document.querySelectorAll<HTMLButtonElement>('[data-product]').forEach(button => button.onclick = () => { const product = state.menu.find(item => item.id === button.dataset.product)!; const variant = product.variants[0]; const line = state.cart.find(item => item.product.id === product.id && item.variant.id === variant.id); if (line) line.quantity++; else state.cart.push({ product, variant, quantity: 1 }); render(); }); document.querySelectorAll<HTMLButtonElement>('[data-cart]').forEach(button => button.onclick = () => { const index = Number(button.dataset.cart); state.cart[index].quantity += Number(button.dataset.change); if (state.cart[index].quantity < 1) state.cart.splice(index, 1); render(); }); document.querySelector('#send-order')?.addEventListener('click', sendOrder); }
async function sendOrder(): Promise<void> { if (!state.branch || !state.cart.length) return; setBusy(true); try { const key = `web-${crypto.randomUUID()}`; const order = await api<{ data: { id: string } }>('/api/v1/orders', { method: 'POST', body: JSON.stringify({ branchId: state.branch.id, tableId: (document.querySelector('#table') as HTMLSelectElement).value || undefined, channel: 'DINE_IN', idempotencyKey: key }) }); for (const line of state.cart) await api(`/api/v1/orders/${order.data.id}/items`, { method: 'POST', body: JSON.stringify({ productId: line.product.id, variantId: line.variant.id, quantity: line.quantity }) }); await api(`/api/v1/orders/${order.data.id}/confirm`, { method: 'POST' }); await api(`/api/v1/orders/${order.data.id}/send-to-kitchen`, { method: 'POST', body: JSON.stringify({ idempotencyKey: `${key}-kitchen` }) }); state.cart = []; state.error = ''; state.loading = false; render(); } catch (error) { showError(error); } }
function bindKitchen(): void { document.querySelector('#refresh-kitchen')?.addEventListener('click', loadKitchen); document.querySelectorAll<HTMLButtonElement>('[data-kitchen]').forEach(button => button.onclick = () => changeKitchen(button.dataset.kitchen!, button.dataset.id!)); }
async function loadKitchen(): Promise<void> { if (!state.branch) return; try { const result = await api<{ data: KitchenTicket[] }>(`/api/v1/branches/${state.branch.id}/kitchen/orders`); state.kitchen = await Promise.all(result.data.map(async ticket => (await api<{ data: KitchenTicket }>(`/api/v1/kitchen/orders/${ticket.id}`)).data)); state.kitchenPending = false; state.connected = true; render(); } catch (error) { state.kitchenPending = error instanceof Error && /404|ruta|not found/i.test(error.message); state.connected = !state.kitchenPending; if (!state.kitchenPending) showError(error); else render(); } }
function connectKitchenStream(): void { kitchenStream?.close(); if (!state.branch || state.view !== 'cocina') return; kitchenStream = new EventSource(`/api/v1/branches/${state.branch.id}/kitchen/events`); const refresh = () => loadKitchen(); kitchenStream.addEventListener('order.sent_to_kitchen', refresh); kitchenStream.addEventListener('order.kitchen_status_changed', refresh); kitchenStream.onmessage = refresh; kitchenStream.onerror = () => { kitchenStream?.close(); kitchenStream = undefined; }; }
async function changeKitchen(action: string, id: string): Promise<void> { try { await api(`/api/v1/kitchen/orders/${id}/${action}`, { method: 'POST', body: JSON.stringify({ idempotencyKey: `web-kitchen-${id}-${action}-${crypto.randomUUID()}` }) }); await loadKitchen(); } catch (error) { showError(error); } }
async function loadSession(): Promise<void> { try { const result = await api<{ user: User }>('/api/v1/auth/me'); state.user = result.user; state.loading = false; const branches = await api<{ data: Branch[] }>('/api/v1/branches'); state.branches = branches.data; state.branch = state.branches[0]; state.connected = true; render(); await loadBranchData(); } catch (error) { state.loading = false; showError(error); } }
async function loadBranchData(): Promise<void> { if (!state.branch) return; setBusy(true); try { const [menu, tables] = await Promise.all([api<{ data: Product[] }>(`/api/v1/branches/${state.branch.id}/menu`), api<{ data: Table[] }>(`/api/v1/branches/${state.branch.id}/tables`)]); state.menu = menu.data; state.tables = tables.data; state.connected = true; state.loading = false; render(); if (state.view === 'cocina') { loadKitchen(); connectKitchenStream(); } } catch (error) { state.loading = false; showError(error); } }
window.addEventListener('online', () => { state.connected = true; render(); }); window.addEventListener('offline', () => { state.connected = false; render(); });
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined);
render(); loadSession();
setInterval(() => { if (state.user && state.view === 'cocina' && state.branch) loadKitchen(); }, 15000);